Repository google/mobly-bundled-snippets, pull requests merged in 2022-01, with the labels that each got.

#145 Fix typo
  src/main/java/com/google/android/mobly/snippet/bundled/bluetooth/BluetoothAdapterSnippet.java
Labels: docs

#146 Have wifiClearConfiguredNetworks re-check network list to determine operation success.
  src/main/java/com/google/android/mobly/snippet/bundled/WifiManagerSnippet.java
Labels: bug

#147 Adds stream type STREAM_ALARM methods.
  src/main/java/com/google/android/mobly/snippet/bundled/AudioSnippet.java
Labels: improvement
