Repository google/mobly-bundled-snippets, pull requests merged in 2023-12, with the labels that each got.

#180 Update version check for deprecated getCallState and getNetworkType
  src/main/java/com/google/android/mobly/snippet/bundled/TelephonySnippet.java
Labels: improvement

#179 Refactor manufacturerSpecificData to ManufacturerSpecificData
  src/main/java/com/google/android/mobly/snippet/bundled/utils/JsonDeserializer.java
Labels: refactor

#181 Fix error: package Build does not exist
  src/main/java/com/google/android/mobly/snippet/bundled/TelephonySnippet.java
Labels: bug
