Repository google/mobly-bundled-snippets, pull requests merged in 2024-08, with the labels that each got.

#199 Fix MBS Utils to work while being instrumented
  src/main/java/com/google/android/mobly/snippet/bundled/utils/Utils.java
Labels: improvement

#203 Add new snippet for adding a contact with the given email address
  src/main/AndroidManifest.xml
  src/main/java/com/google/android/mobly/snippet/bundled/ContactSnippet.java
Labels: new feature

#202 Update WifiManagerSnippet.java
  src/main/java/com/google/android/mobly/snippet/bundled/WifiManagerSnippet.java
Labels: improvement

#209 Rename RPC methods with wifi prefix.
  src/main/java/com/google/android/mobly/snippet/bundled/WifiAwareManagerSnippet.java
  src/main/java/com/google/android/mobly/snippet/bundled/WifiManagerSnippet.java
Labels: refactor

#204 Add new snippet for removing a contact with the given email address
  src/main/java/com/google/android/mobly/snippet/bundled/ContactSnippet.java
Labels: new feature

#210 Remove unused android.content.pm.PackageManager
  src/main/java/com/google/android/mobly/snippet/bundled/WifiManagerSnippet.java
Labels: refactor
