Repository google/mobly-bundled-snippets, pull requests merged in 2025-03, with the labels that each got.

#223 Add RpcEnum::getIntBitwiseOr() Helper API (1/3)
  build.gradle
  src/main/java/com/google/android/mobly/snippet/bundled/utils/MbsEnums.java
  src/main/java/com/google/android/mobly/snippet/bundled/utils/RpcEnum.java
  src/test/java/MbsEnumsTest.java
Labels: new feature

#228 Check BluetoothAdapter#getProfileProxy return value and fix MissingOv…
  src/main/java/com/google/android/mobly/snippet/bundled/bluetooth/profiles/BluetoothA2dpSnippet.java
  src/main/java/com/google/android/mobly/snippet/bundled/bluetooth/profiles/BluetoothHeadsetSnippet.java
  src/main/java/com/google/android/mobly/snippet/bundled/bluetooth/profiles/BluetoothHearingAidSnippet.java
  src/main/java/com/google/android/mobly/snippet/bundled/bluetooth/profiles/BluetoothLeAudioSnippet.java
Labels: improvement

#232 Add new RPCs for checking live audio route info
  src/main/java/com/google/android/mobly/snippet/bundled/MediaSnippet.java
Labels: new feature

#233 Support for specifying BSSID in Wi-Fi config
  src/main/java/com/google/android/mobly/snippet/bundled/utils/JsonDeserializer.java
Labels: new feature

#235 Add Unit Test for JsonDeserializer.java
  src/test/java/JsonDeserializerTest.java
Labels: testing
